language: java

# So that SonarCloud can see the whole history
git:
  depth: false

matrix:
  fast_finish: true
  include:
    # always build this environment
    - os: linux
      dist: xenial
      jdk: openjdk8
      services:
      - xvfb
      env: ADDITIONAL="-Pjacoco,build-ide,test-ide,run-its coveralls:report sonar:sonar"
    # only on PR, or after merging a PR
    - os: osx
      osx_image: xcode10.1
      jdk: openjdk11
      env: ADDITIONAL="-Pbuild-ide,test-ide,run-its"
      if: type IN (pull_request) OR commit_message =~ /^Merge pull request/

addons:
  sonarcloud:
    organization: "lorenzobettini-github"
    token:
      secure: $SONAR_TOKEN

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.sonar/cache'

install: true

before_install:
# - echo "MAVEN_OPTS='-Xmx768m -Xms256m -Xss1m'" > ~/.mavenrc
# - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
 - echo $JAVA_HOME

before_script:
 - find $HOME/.m2/repository -name "*edelta*" -exec rm -rf {} \+ || true

# Build on MacOSX is triggered only for pull requests and merge of pull requests
script:
 - export
 - ./mvnw -f edelta.parent/pom.xml clean verify $ADDITIONAL

before_cache:
 - find $HOME/.m2/repository -name "*edelta*" -exec rm -rf {} \+

after_success:
 - find ./edelta.parent/edelta.ui.tests/target/ -name "*.log"

after_failure:
# - find ./edelta.parent/*/target/work/ -name "*.log" -exec cat {} \;
 - find ./edelta.parent/*/target/it/ -name "*.log" -exec cat {} \;
